apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T01:16:10Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "7061"
  uid: e263aae3-97de-4622-a2d2-2b88a9276165
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.132.99
  clusterIPs:
  - 10.98.132.99
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30441
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
